window.VORZELI_ICON_MAP = {
  'Acessórios para Celular': {
    'Capinhas': 'icons/acessorios-para-celular__capinhas.svg',
    'Películas': 'icons/acessorios-para-celular__peliculas.svg',
    'Cabos': 'icons/acessorios-para-celular__cabos.svg',
    'Carregadores': 'icons/acessorios-para-celular__carregadores.svg',
    'Fones': 'icons/acessorios-para-celular__fones.svg',
    'Power Banks': 'icons/acessorios-para-celular__power-banks.svg',
    'Suportes': 'icons/acessorios-para-celular__suportes.svg',
    'Adaptadores': 'icons/acessorios-para-celular__adaptadores.svg',
  },
  'Smartwatches e Acessórios': {
    'Smartwatches': 'icons/smartwatches-e-acessorios__smartwatches.svg',
    'Smartbands': 'icons/smartwatches-e-acessorios__smartbands.svg',
    'Pulseiras': 'icons/smartwatches-e-acessorios__pulseiras.svg',
    'Películas': 'icons/smartwatches-e-acessorios__peliculas.svg',
    'Protetores': 'icons/smartwatches-e-acessorios__protetores.svg',
    'Cabos': 'icons/smartwatches-e-acessorios__cabos.svg',
    'Carregadores': 'icons/smartwatches-e-acessorios__carregadores.svg',
    'Bases': 'icons/smartwatches-e-acessorios__bases.svg',
  },
  'Copos e Térmicos': {
    'Copo térmico inox': 'icons/copos-e-termicos__copo-termico-inox.svg',
    'Copo térmico com tampa': 'icons/copos-e-termicos__copo-termico-com-tampa.svg',
    'Copo com canudo': 'icons/copos-e-termicos__copo-com-canudo.svg',
    'Personalizados': 'icons/copos-e-termicos__personalizados.svg',
    'Canecas': 'icons/copos-e-termicos__canecas.svg',
    'Garrafas térmicas': 'icons/copos-e-termicos__garrafas-termicas.svg',
    'Squeezes': 'icons/copos-e-termicos__squeezes.svg',
    'Acessórios': 'icons/copos-e-termicos__acessorios.svg',
  },
  'Informática e Acessórios': {
    'Mouse': 'icons/informatica-e-acessorios__mouse.svg',
    'Teclados': 'icons/informatica-e-acessorios__teclados.svg',
    'Mouse Pads': 'icons/informatica-e-acessorios__mouse-pads.svg',
    'Hub USB': 'icons/informatica-e-acessorios__hub-usb.svg',
    'Cabos HDMI': 'icons/informatica-e-acessorios__cabos-hdmi.svg',
    'Adaptadores': 'icons/informatica-e-acessorios__adaptadores.svg',
    'Leitores de cartão': 'icons/informatica-e-acessorios__leitores-de-cartao.svg',
    'Suportes': 'icons/informatica-e-acessorios__suportes.svg',
  },
  'Componentes Eletrônicos': {
    'Capacitores': 'icons/componentes-eletronicos__capacitores.svg',
    'Resistores': 'icons/componentes-eletronicos__resistores.svg',
    'LEDs': 'icons/componentes-eletronicos__leds.svg',
    'Fusíveis': 'icons/componentes-eletronicos__fusiveis.svg',
    'Conectores': 'icons/componentes-eletronicos__conectores.svg',
    'Fontes': 'icons/componentes-eletronicos__fontes.svg',
    'Módulos': 'icons/componentes-eletronicos__modulos.svg',
    'Cabos': 'icons/componentes-eletronicos__cabos.svg',
  },
  'Ferramentas': {
    'Chaves': 'icons/ferramentas__chaves.svg',
    'Alicates': 'icons/ferramentas__alicates.svg',
    'Bits': 'icons/ferramentas__bits.svg',
    'Trenas': 'icons/ferramentas__trenas.svg',
    'Estiletes': 'icons/ferramentas__estiletes.svg',
    'Pinças': 'icons/ferramentas__pincas.svg',
    'Ferro de solda': 'icons/ferramentas__ferro-de-solda.svg',
    'Sugador': 'icons/ferramentas__sugador.svg',
    'Multímetros': 'icons/ferramentas__multimetros.svg',
  },
  'Casa e Utilidades': {
    'Organizadores': 'icons/casa-e-utilidades__organizadores.svg',
    'Cozinha': 'icons/casa-e-utilidades__cozinha.svg',
    'Banheiro': 'icons/casa-e-utilidades__banheiro.svg',
    'Ganchos': 'icons/casa-e-utilidades__ganchos.svg',
    'Acessórios para Air Fryer': 'icons/casa-e-utilidades__acessorios-para-air-fryer.svg',
    'Utilidades domésticas': 'icons/casa-e-utilidades__utilidades-domesticas.svg',
  },
  'Brinquedos': {
    'Educativos': 'icons/brinquedos__educativos.svg',
    'Blocos de montar': 'icons/brinquedos__blocos-de-montar.svg',
    'Carrinhos': 'icons/brinquedos__carrinhos.svg',
    'Quebra-cabeças': 'icons/brinquedos__quebra-cabecas.svg',
    'Jogos de memória': 'icons/brinquedos__jogos-de-memoria.svg',
    'Kits de desenho': 'icons/brinquedos__kits-de-desenho.svg',
    'Sensoriais': 'icons/brinquedos__sensoriais.svg',
    'Interativos': 'icons/brinquedos__interativos.svg',
  },
  'Acessórios Automotivos': {
    'Suportes': 'icons/acessorios-automotivos__suportes.svg',
    'Carregadores veiculares': 'icons/acessorios-automotivos__carregadores-veiculares.svg',
    'Cabos': 'icons/acessorios-automotivos__cabos.svg',
    'Adaptadores': 'icons/acessorios-automotivos__adaptadores.svg',
    'Organizadores': 'icons/acessorios-automotivos__organizadores.svg',
    'Microfibra': 'icons/acessorios-automotivos__microfibra.svg',
    'Limpeza': 'icons/acessorios-automotivos__limpeza.svg',
    'Acessórios': 'icons/acessorios-automotivos__acessorios.svg',
  },
  'Games e Acessórios': {
    'Mouse gamer': 'icons/games-e-acessorios__mouse-gamer.svg',
    'Mouse Pads': 'icons/games-e-acessorios__mouse-pads.svg',
    'Suportes para headset': 'icons/games-e-acessorios__suportes-para-headset.svg',
    'Cabos para controles': 'icons/games-e-acessorios__cabos-para-controles.svg',
    'Capas para controles': 'icons/games-e-acessorios__capas-para-controles.svg',
    'Grips': 'icons/games-e-acessorios__grips.svg',
    'Suportes para controles': 'icons/games-e-acessorios__suportes-para-controles.svg',
    'Jogos mobile': 'icons/games-e-acessorios__jogos-mobile.svg',
  },
  'Áudio e Acessórios': {
    'Fones Bluetooth': 'icons/audio-e-acessorios__fones-bluetooth.svg',
    'Fones com fio': 'icons/audio-e-acessorios__fones-com-fio.svg',
    'Cabos P2': 'icons/audio-e-acessorios__cabos-p2.svg',
    'Adaptadores de áudio': 'icons/audio-e-acessorios__adaptadores-de-audio.svg',
    'Cabos auxiliares': 'icons/audio-e-acessorios__cabos-auxiliares.svg',
    'Microfones': 'icons/audio-e-acessorios__microfones.svg',
    'Suportes para fones': 'icons/audio-e-acessorios__suportes-para-fones.svg',
  },
  'Iluminação': {
    'Fitas LED': 'icons/iluminacao__fitas-led.svg',
    'Lâmpadas LED': 'icons/iluminacao__lampadas-led.svg',
    'Luminárias USB': 'icons/iluminacao__luminarias-usb.svg',
    'Luzes noturnas': 'icons/iluminacao__luzes-noturnas.svg',
    'Luminárias de mesa': 'icons/iluminacao__luminarias-de-mesa.svg',
    'Sensores': 'icons/iluminacao__sensores.svg',
    'Soquetes': 'icons/iluminacao__soquetes.svg',
    'Adaptadores': 'icons/iluminacao__adaptadores.svg',
  },
  'Pet e Acessórios': {
    'Brinquedos': 'icons/pet-e-acessorios__brinquedos.svg',
    'Comedouros': 'icons/pet-e-acessorios__comedouros.svg',
    'Bebedouros': 'icons/pet-e-acessorios__bebedouros.svg',
    'Escovas': 'icons/pet-e-acessorios__escovas.svg',
    'Coleiras': 'icons/pet-e-acessorios__coleiras.svg',
    'Guias': 'icons/pet-e-acessorios__guias.svg',
    'Higiene': 'icons/pet-e-acessorios__higiene.svg',
    'Acessórios': 'icons/pet-e-acessorios__acessorios.svg',
  },
  'Audiologia — Acessórios e Componentes': {
    'Audiômetro': 'icons/audiologia-acessorios-e-componentes__audiometro.svg',
    'Imitanciômetro': 'icons/audiologia-acessorios-e-componentes__imitanciometro.svg',
    'BERA / PEATE': 'icons/audiologia-acessorios-e-componentes__bera-peate.svg',
    'Vecto / VENG': 'icons/audiologia-acessorios-e-componentes__vecto-veng.svg',
  },
  'Medicina — Acessórios e Componentes': {
    'ECG': 'icons/medicina-acessorios-e-componentes__ecg.svg',
    'EEG': 'icons/medicina-acessorios-e-componentes__eeg.svg',
    'Espirometria': 'icons/medicina-acessorios-e-componentes__espirometria.svg',
  },
};

window.vorzeliIcon = function(area, name) {
  const map = window.VORZELI_ICON_MAP || {};
  return (map[area] && map[area][name]) || "";
};

window.vorzeliIconHTML = function(area, name) {
  const src = window.vorzeliIcon(area, name);
  if (!src) return "";
  return `<img class="vorzeliIcon" src="${src}" alt="" aria-hidden="true">`;
};
